mysqldb:
  image: mysql:5.7
  environment:
   - MYSQL_ROOT_PASSWORD=282713Fx
   - MYSQL_DATABASE=db
  restart: unless-stopped

gameserver:
  image: zhumao:latest
  ports:
    - 5000:5000/tcp
    - 5000:5000/udp
  # net: "host"
  links:
    - mysqldb
  restart: unless-stopped